[package]
name = "norwegian-literarycollection-sonans"
version = "0.1.0"
authors = ["Sigurd Berg Svela <sigurdbergsvela@gmail.com>"]
edition = "2018"
src = "build/src"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
